name: Deploy to Workshop

on:
  workflow_dispatch:
    inputs:
      changelog:
        type: string
        required: false
        default: "Update to latest Git commit"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: project

      - uses: CFC-Servers/gmod-upload@master
        with:
          id: 3114947614
          changelog: ${{ inputs.changelog }}
          title: CFC Lag Alerter
          type: ServerContent
          tag1: build
          remove_lua: true
        env:
          STEAM_USERNAME: ${{ secrets.WORKSHOP_UPLOADER_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.WORKSHOP_UPLOADER_PASSWORD }}
